### ISSUE TITLE
Update all ROS packages to use this copy of FindTinyXML.cmake

### ISSUE THREAD

**Issue by wjwwood** [ros/cmake_modules#4]
These are the ROS packages which need touching (all I could find):
- [x] `rospack` https://github.com/ros/rospack/issues/24 @dirk-thomas
- [x] `pluginlib` https://github.com/ros/pluginlib/issues/18 @mirzashah @esteve
- [x] `collada_urdf` https://github.com/ros/robot_model/issues/30 @isucan
- [x] `kdl_parser` https://github.com/ros/robot_model/issues/30 @isucan
- [x] `urdf` https://github.com/ros/robot_model/issues/30 @isucan
- [x] `srdfdom` https://github.com/ros-planning/srdfdom/issues/4 @isucan
- [x] `ros_control` https://github.com/ros-controls/ros_control/issues/98 @davetcoleman
- [x] `urdfdom` This is not a catkin package, so it will not depend on this package.

You can see how to use this package:

https://github.com/ros/cmake_modules/blob/master/README.md#usage

And an example package:

https://github.com/ros/cmake_modules/tree/master/tests/test_find_tinyxml

**Comment by isucan** [comment]
one more i think should be added to the list:
- [x] `srdfdom`

**Comment by wjwwood** [comment]
Ok, is that a catkin package? If not, it probably isn't very convenient to depend on this package.

**Comment by isucan** [comment]
it is a catkin package.

**Comment by wjwwood** [comment]
I added it to the list and opened an issue.

**Comment by davetcoleman** [comment]
another:
`ros_control`

**Comment by wjwwood** [comment]
I added it to the list too.

**Comment by dirk-thomas** [comment]
rospack - checked.

**Comment by tfoote** [comment]
ros_control checked due to https://github.com/ros-controls/ros_control/issues/105
